
import 'dart:convert';
import 'api_model.dart';
import 'package:http/http.dart' as http;

Future<Autogenerated?> fetchData() async {
  const url = 'https://reqres.in/api/users/2'; // Replace with your API endpoint
  try {
    final response = await http.get(Uri.parse(url));
    if (response.statusCode == 200) {
      final jsonMap = json.decode(response.body);
      final user = Autogenerated.fromJson(jsonMap);
      print(user.data?.email);
      return user;
    } else {
      // Handle errors
      print('Error: ${response.statusCode}');
      return null;
    }
  } catch (e) {
    // Handle any exceptions that occur during the API call
    print('Exception: $e');
    return null;
  }
}
